name=CoVACIEL
version=0.0.3
author=Francois Riotte
maintainer=FR
sentence=Gestion des actionneurs (propulsion et direction), des capteurs (TOF ou lidar) et du BUS CAN pour le projet CoVACIEL
paragraph=
category=Communication
url= https://github.com/rgot-org/CoVACIEL-ESP32
architectures=esp32
depends=ArduinoJson (>=7.3.0)
